name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Read Ruby version
      id: rubyver
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.ruby-version
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ steps.rubyver.outputs.content }}
    - name: Install Gosu dependencies
      run: sudo apt-get install build-essential libsdl2-dev libgl1-mesa-dev libopenal-dev libsndfile-dev libmpg123-dev libgmp-dev libfontconfig1-dev
    - name: Build and lint with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake lint
