name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Read Ruby version
      id: rubyver
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.ruby-version

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ steps.rubyver.outputs.content }}

    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3

    - name: Lint files
      run: bundle exec rake rubocop
