name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Read Ruby version
      id: rubyver
      uses: juliangruber/read-file-action@v1
      with:
        path: ./.ruby-version
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ steps.rubyver.outputs.content }}
    - name: Build and lint with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake lint
